"""Canonical keys used by instrument runtime dictionaries."""

from __future__ import annotations

DF_KEY = "df"
FIG_KEY = "fig"
FIG_DIST_KEY = "fig_dist"
FIG_STRIP_KEY = "fig_strip"
SRC_IMG_KEY = "src_img"
SRC_DIST_KEY = "src_dist"
MAPPER_KEY = "mapper"
COLORBAR_KEY = "colorbar"
IMG_RENDERER_KEY = "img_renderer"
POLYGON_KEY = "polygons"
SELECTED_POLY_KEY = "selected_poly"
POLY_SRC_KEY = "poly_src"
POLY_BG_SRC_KEY = "poly_bg_src"
RECT_SRC_KEY = "rect_src"
OVERLAY_KEY = "overlay_var_lines"
OVERLAY_VAR_CONTAINER_KEY = "overlay_var_container"
ADD_OVERLAY_VAR_BTN_KEY = "btn_add_overlay_var"
FIT_LINE_SRCS_KEY = "fit_line_srcs"
FIT_LINE_RENDERERS_KEY = "fit_line_renderers"
FIT_RENDERERS_KEY = "fit_renderers"
UNDO_STACK_KEY = "undo_stack"
MODE_MULTI_SRC_KEY = "mode_multi_src"
MODE_SUM_SRC_KEY = "mode_sum_src"
MODE_FIT_RENDERER_KEY = "mode_fit_renderer"
PATH_INPUT_KEY = "path_input"
LOAD_BUTTON_KEY = "load_btn"
FILE_TYPE_KEY = "type"
FIT_TYPES_KEY = "fit_types"

# Conceptual groups that remain embedded in the instrument dictionary.
FIT_SOURCES_KEY = "fit_sources"
DISTRIBUTION_STATE_KEY = "distribution_state"
HEATMAP_STATE_KEY = "heatmap_state"

HEATMAP_RUNTIME_KEY = "_heatmap_runtime"
POLYGON_RUNTIME_KEY = "_polygon_runtime"
FIT_RUNTIME_KEY = "_fit_runtime"
DISTRIBUTION_RUNTIME_KEY = "_distribution_runtime"
OVERLAY_RUNTIME_KEY = "_overlay_runtime"

WIDGET_CALLBACKS_KEY = "_widget_callbacks"
RENDERER_CALLBACKS_KEY = "_renderer_callbacks"
TOOL_CALLBACKS_KEY = "_tool_callbacks"
DOCUMENT_CALLBACKS_KEY = "_document_callbacks"

LIFECYCLE_RUNTIME_KEY = "_lifecycle_runtime"
